### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/install-vscode-action#2]
https://github.com/gbraad-actions/actions-test/blob/ace5ba5316895f5068c8eeb305838d9e216e6c98/.github/workflows/windows-rdp-test.yml#L6

```yaml
on:
  workflow_dispatch:

jobs:
  test:

    runs-on: windows-latest
    steps:

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENTID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:actions

      - uses: gbraad-actions/install-vscode-action@main
      - name: Run VS Code serve-web
        run: |
          code serve-web --host 0.0.0.0 --without-connection-token
```
